/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Ein Vermisstenabgleich (1:1 zu `person_abgleich`). */
        AbgleichAnzeige: {
            /** Format: int64 */
            einsatz_id: number;
            entschieden_at?: string | null;
            /** Format: int64 */
            entschieden_von?: number | null;
            erstellt_at: string;
            /** Format: int64 */
            erstellt_von: number;
            /** Format: int64 */
            gefunden_person_id: number;
            /** Format: int64 */
            id: number;
            status: components["schemas"]["AbgleichStatus"];
            /** Format: int64 */
            vermisst_person_id: number;
        };
        /**
         * @description Abgleich-Status (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `status`.
         * @enum {string}
         */
        AbgleichStatus: "verdacht" | "bestaetigt" | "verworfen";
        /**
         * @description Abschlussgrund beim Übergang `→ abgeschlossen`. String = CHECK-Constraint.
         *     `etb_label` erscheint in Klammern in der ETB-Spur (Spec: "abgeschlossen
         *     (uebergabe_tierarzt)") — daher identisch zum DB-String.
         * @enum {string}
         */
        AbschlussGrund: "uebergabe_halter" | "uebergabe_tierarzt" | "uebergabe_tierheim" | "verstorben" | "freilauf" | "sonstiges";
        /**
         * @description Geteilte externe Adressat-Kategorie für Nachforderung (`adressat_kategorie`) und Auftrag
         *     (`extern_kategorie`) (Schema-Anker für die OpenAPI-Union, LFH-120).
         * @enum {string}
         */
        AdressatKategorie: "leitstelle" | "nachbar_ea" | "uebergeordnet" | "andere_bos";
        /**
         * @description Öffentliche Darstellung eines Anhangs — ohne die Bytes (`daten`), die nur
         *     über den Download-Endpoint ausgeliefert werden.
         */
        AnhangAnzeige: {
            dateiname: string;
            /** Format: int64 */
            einsatz_id: number;
            erstellt_at: string;
            /** Format: int64 */
            groesse: number;
            /** Format: int64 */
            hochgeladen_von: number;
            /** Format: int64 */
            id: number;
            mime: string;
        };
        /**
         * @description Anzeige eines Auftrags inkl. abgeleiteter Felder und der Vollzugs-Achse aus
         *     dem geteilten `kommunikation_status` (per LEFT JOIN). Quittungs-Aggregate
         *     (`empfaenger_anzahl`, `quittiert_anzahl`) stammen aus `auftrag_empfaenger`.
         */
        AuftragAnzeige: {
            abgenommen_at?: string | null;
            /** Format: int64 */
            abgenommen_von_id?: number | null;
            absicht?: string | null;
            auftrag_text: string;
            bearbeitungsstatus: components["schemas"]["AuftragBearbeitungsstatus"];
            /** Format: int64 */
            einsatz_id: number;
            /** Format: int64 */
            empfaenger_anzahl: number;
            erstellt_at: string;
            /** Format: int64 */
            erstellt_von_id: number;
            erteilt_at: string;
            /** Format: int64 */
            etb_anordnung_id?: number | null;
            frist_at?: string | null;
            /** Format: int64 */
            id: number;
            in_arbeit_at?: string | null;
            ist_ueberfaellig: boolean;
            lage?: string | null;
            /**
             * Format: int64
             * @description Laufende Nummer je Einsatz (LFH-133). Nullable, weil per ADD COLUMN eingeführt;
             *     alle ab LFH-133 angelegten Aufträge tragen einen Wert.
             */
            lfd_nr?: number | null;
            mittel?: string | null;
            ort?: string | null;
            prioritaet: components["schemas"]["Prioritaet"];
            /**
             * Format: int64
             * @description Quell-ETB-Eintrag, AUS DEM dieser Auftrag erteilt wurde (LFH-112). Klar getrennt
             *     von `etb_anordnung_id` (= der vom Auftrag SELBST erzeugte Anordnungs-Eintrag).
             */
            quell_etb_eintrag_id?: number | null;
            /** Format: int64 */
            quittiert_anzahl: number;
            /** @description Richtung intern/extern (LFH-87). */
            richtung: components["schemas"]["Richtung"];
            sicherheit?: string | null;
            verbindung?: string | null;
            vollzogen_at?: string | null;
            /** Format: int64 */
            vollzogen_von_id?: number | null;
            vollzug_status: string;
            vollzugsmeldung?: string | null;
            zeit?: string | null;
        };
        /**
         * @description Bearbeitungsstatus eines Auftrags (Schema-Anker für die OpenAPI-Union, LFH-120).
         *     Wire == `bearbeitungsstatus`.
         * @enum {string}
         */
        AuftragBearbeitungsstatus: "offen" | "in_arbeit" | "vollzogen" | "abgenommen";
        /** @description Auftrag + seine Empfänger (Detail-/Anlege-/Mutations-Antwort). */
        AuftragDetail: components["schemas"]["AuftragAnzeige"] & {
            empfaenger: components["schemas"]["AuftragEmpfaengerAnzeige"][];
        };
        /** @description Anzeige einer Empfänger-Zeile inkl. Quittung (Achse 1, pro Empfänger). */
        AuftragEmpfaengerAnzeige: {
            /** Format: int64 */
            abschnitt_id?: number | null;
            /** Format: int64 */
            auftrag_id: number;
            /** Format: int64 */
            einheit_id?: number | null;
            empfaenger_typ: components["schemas"]["EmpfaengerTyp"];
            extern_bezeichnung?: string | null;
            extern_kategorie?: null | components["schemas"]["AdressatKategorie"];
            /** Format: int64 */
            fahrzeug_id?: number | null;
            funktion_text?: string | null;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            person_id?: number | null;
            quittiert_at?: string | null;
            /** Format: int64 */
            quittiert_von_id?: number | null;
            snap_anzeige: string;
        };
        /** @enum {string} */
        Ausmass: "gering" | "mittel" | "gross" | "katastrophal";
        /** @description Öffentliche Darstellung eines Providers für die Login-UI (`GET /api/auth/providers`). */
        AuthProviderAnzeige: {
            aktiviert: boolean;
            /** @description Menschenlesbarer Anzeigename für Buttons/Labels. */
            anzeigename: string;
            /** @description Stabile ID (z.B. "passwort", "dev"). */
            id: string;
            typ: components["schemas"]["AuthProviderTyp"];
        };
        /**
         * @description Art eines Auth-Providers — bestimmt, wie das Frontend den Login rendert.
         *     Wire == snake_case (Enum-Wire-Kontrakt).
         * @enum {string}
         */
        AuthProviderTyp: "passwort" | "dev" | "oidc" | "webauthn";
        /**
         * @description Basemap-Modus (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `basemap_modus`.
         * @enum {string}
         */
        BasemapModus: "online" | "offline" | "blind";
        /** @description Ein gefüllter Abschnitt (so persistiert als JSON-Array-Element). */
        BefehlAbschnitt: {
            schluessel: string;
            text: string;
        };
        /** @description Öffentliche Anzeige eines Befehls (Abschnitte aus JSON geparst, Namen aufgelöst). */
        BefehlAnzeige: {
            abschnitte: components["schemas"]["BefehlAbschnitt"][];
            aktualisiert_at: string;
            /** Format: int64 */
            einsatz_id: number;
            /** Format: int64 */
            ersteller_id: number;
            ersteller_name: string;
            erstellt_at: string;
            /** Format: int64 */
            etb_eintrag_id?: number | null;
            freigegeben_at?: string | null;
            /** Format: int64 */
            freigegeben_von_id?: number | null;
            freigegeben_von_name?: string | null;
            /** Format: int64 */
            id: number;
            status: components["schemas"]["BefehlStatus"];
            titel: string;
            /** Format: int64 */
            version: number;
            /** Format: int64 */
            vorgaenger_id?: number | null;
            vorlage: components["schemas"]["BefehlVorlage"];
            zeitstand: string;
        };
        /**
         * @description Befehls-Status (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `status`.
         * @enum {string}
         */
        BefehlStatus: "entwurf" | "freigegeben";
        /**
         * @description Befehls-Vorlage (Schema-Anker für die OpenAPI-Union, LFH-120; TS: `BefehlVorlageKey`).
         *     Wire == `vorlage`.
         * @enum {string}
         */
        BefehlVorlage: "befehl_lad" | "befehl_ladef" | "befehl_schnee" | "befehl_ea_zmw";
        /** @description Belegungs-Verlaufseintrag (1:1 zu `person_uhs_belegung`). */
        BelegungAnzeige: {
            art: components["schemas"]["BelegungsArt"];
            /** Format: int64 */
            einsatz_id: number;
            /** Format: int64 */
            erfasst_von: number;
            /** Format: int64 */
            id: number;
            notiz?: string | null;
            /** Format: int64 */
            person_id: number;
            /** Format: int64 */
            platz_id?: number | null;
            /** Format: int64 */
            uhs_id: number;
            zeitpunkt_at: string;
        };
        /**
         * @description Art eines Belegungs-Events. String = CHECK in
         *     `migrations/0029_person_uhs_belegung.sql`. Append-only.
         * @enum {string}
         */
        BelegungsArt: "eintritt" | "wechsel" | "austritt";
        /** @description Öffentliche Benutzerdarstellung (ohne Passwort-Hash) für API-Antworten. */
        BenutzerAnzeige: {
            aktiv: boolean;
            anzeigename: string;
            benutzername: string;
            erstellt_at: string;
            /** Format: int64 */
            id: number;
            org_rolle: components["schemas"]["OrgRolle"];
            system_rolle: components["schemas"]["SystemRolle"];
            /**
             * @description MFA-Status (LFH-43, Increment 5 Task 6): `true`, wenn der Nutzer TOTP als zweiten Faktor
             *     aktiviert hat. Zeigt sowohl der Admin-Benutzerliste als auch dem eigenen Profil
             *     (`GET /api/auth/me`) den Status an.
             */
            totp_aktiviert: boolean;
        };
        /**
         * @description Betriebsart einer TETRA-Sprechgruppe (Schema-Anker für die OpenAPI-Union, LFH-120).
         *     Wire == `betriebsart` (per-Variante, Großbuchstaben — `rename_all` trifft nicht).
         * @enum {string}
         */
        Betriebsart: "TMO" | "DMO";
        /**
         * @description Typ des polymorphen Sachbezugs einer Nachricht (LFH-103). Code-validiert (kein
         *     DB-CHECK, analog `auftrag.prioritaet`/`meldung.status`); die Codes sind die
         *     Modulnamen der referenzierbaren Domänenobjekte. Bewusst getrennt von der
         *     Heraufstufung (`etb_eintrag_id`/`auftrag_id`): ein Bezug verweist auf ein
         *     bestehendes Objekt, eine Heraufstufung erzeugt eines.
         * @enum {string}
         */
        BezugTyp: "schaden" | "uhs" | "person" | "lagebericht" | "meldung" | "auftrag";
        /** @description Serialisierbare BR-Anzeige (1:1 zur Tabelle `bereitstellungsraum`). */
        BrAnzeige: {
            /** Format: int64 */
            abschnitt_id?: number | null;
            bezeichnung: string;
            /** Format: int64 */
            einsatz_id: number;
            erfasst_at: string;
            /** Format: int64 */
            erfasst_von: number;
            geaendert_at: string;
            /** Format: int64 */
            geaendert_von: number;
            /** Format: int64 */
            id: number;
            notiz?: string | null;
            standort?: string | null;
            status: components["schemas"]["BrStatus"];
            storniert_at?: string | null;
        };
        /** @description Belegungs-Verlaufseintrag (1:1 zu `br_belegung`). */
        BrBelegungAnzeige: {
            art: components["schemas"]["BrBelegungsArt"];
            /** Format: int64 */
            br_id: number;
            /** Format: int64 */
            einsatz_id: number;
            /** Format: int64 */
            erfasst_von: number;
            /** Format: int64 */
            id: number;
            notiz?: string | null;
            /** Format: int64 */
            objekt_id: number;
            objekt_typ: components["schemas"]["ObjektTyp"];
            zeitpunkt_at: string;
        };
        /**
         * @description Art eines BR-Belegungs-Events. String = CHECK-Constraint in
         *     `migrations/0061_br_belegung.sql`. Append-only.
         * @enum {string}
         */
        BrBelegungsArt: "eintritt" | "wechsel" | "austritt";
        /** @description Detail-Antwort: BR-Stamm + aktuell bereitgestellte Einheiten + Fahrzeuge. */
        BrDetail: components["schemas"]["BrAnzeige"] & {
            einheiten: components["schemas"]["BrEinheitKurz"][];
            fahrzeuge: components["schemas"]["BrFahrzeugKurz"][];
        };
        /** @description Schlanke Einheiten-Info für den Detail-Response. */
        BrEinheitKurz: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        /** @description Schlanke Fahrzeug-Info für den Detail-Response. */
        BrFahrzeugKurz: {
            funkrufname: string;
            /** Format: int64 */
            id: number;
        };
        /**
         * @description Status eines Bereitstellungsraums. String = CHECK-Constraint in
         *     `migrations/0060_bereitstellungsraum.sql`. `aufgeloest` ist terminal.
         * @enum {string}
         */
        BrStatus: "geplant" | "aktiv" | "aufgeloest";
        /**
         * @description Ein Build-Job des zentralen karten-service (LFH-323, verschoben aus `karten-service`). Damit
         *     läuft der Cross-Service-Vertrag durch die bestehende Codegen-Kette statt als roher
         *     `serde_json::Value` daran vorbei.
         */
        BuildJob: {
            beendet?: string | null;
            gestartet: string;
            /** Format: int64 */
            id: number;
            slug: string;
            /**
             * @description Inline statt `$ref`: [`JobStatus`] ist datentragend und bewusst kein registriertes
             *     Component-Schema — utoipa bettet die Union direkt hier ein.
             */
            status: {
                /** @enum {string} */
                status: "queued";
            } | {
                /** @enum {string} */
                status: "building";
            } | {
                /** @enum {string} */
                status: "uploading";
            } | {
                /** @enum {string} */
                status: "publishing";
            } | {
                /** @enum {string} */
                status: "done";
            } | {
                fehler: string;
                /** @enum {string} */
                status: "failed";
            };
        };
        /** @description Öffentliche Darstellung eines Chat-Kanals. */
        ChatKanalAnzeige: {
            archiviert_at?: string | null;
            beschreibung?: string | null;
            /** Format: int64 */
            einsatz_id: number;
            erstellt_at: string;
            /** Format: int64 */
            erstellt_von_id: number;
            /** Format: int64 */
            id: number;
            name: string;
        };
        /**
         * @description Öffentliche Darstellung einer Chat-Nachricht. `inhalt` ist `None`, wenn die
         *     Nachricht gelöscht wurde (Tombstone) — der Text wird dann nicht ausgeliefert.
         */
        ChatNachrichtAnzeige: {
            /**
             * @description Angehängte Dateien (Metadaten, ohne Bytes). Wird nicht aus der
             *     Nachrichten-Zeile gelesen (`sqlx(skip)`), sondern vom Repo nachgeladen.
             */
            anhaenge: components["schemas"]["AnhangAnzeige"][];
            /** Format: int64 */
            auftrag_id?: number | null;
            /** Format: int64 */
            autor_id: number;
            autor_name: string;
            bearbeitet_at?: string | null;
            /** Format: int64 */
            bezug_id?: number | null;
            bezug_typ?: null | components["schemas"]["BezugTyp"];
            /** Format: int64 */
            einsatz_id: number;
            erstellt_at: string;
            /** Format: int64 */
            etb_eintrag_id?: number | null;
            geloescht_at?: string | null;
            /** Format: int64 */
            id: number;
            inhalt?: string | null;
            /** Format: int64 */
            kanal_id: number;
        };
        /**
         * @description Dienststatus im Stamm (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `dienststatus`.
         * @enum {string}
         */
        Dienststatus: "in_dienst" | "ausser_dienst";
        /**
         * @description Aufgelöste Einheiten-Anzeige inkl. Typ/Abschnitt-Labels, Führer-Identität,
         *     Mitgliedern und berechneter Stärke. `soll` ist optional (Override → Typ-Default →
         *     `None`); `ist`/`ist_kumuliert` sind immer gesetzt.
         */
        EinheitAnzeige: {
            /** Format: int64 */
            abschnitt_id?: number | null;
            abschnitt_name?: string | null;
            /**
             * Format: int64
             * @description BR‑1: aktuell bereitgestellter Bereitstellungsraum (NULL = in keinem BR).
             */
            aktueller_br_id?: number | null;
            bemerkung?: string | null;
            /** Format: int64 */
            einsatz_id: number;
            /** @description Funk/Kommunikation (LFH-108): Rufnummer/Freitext (PII → schwaerze_einsatz). */
            erreichbarkeit?: string | null;
            fahrzeug_mitglieder: components["schemas"]["EinheitMitgliedFahrzeug"][];
            /** Format: int64 */
            fuehrer_id?: number | null;
            fuehrer_name?: string | null;
            /** Format: int64 */
            id: number;
            ist: components["schemas"]["Staerke"];
            ist_kumuliert: components["schemas"]["Staerke"];
            /** @description Funk/Kommunikation (LFH-108): Freitext-Schlüssel (digitalfunk/mobil/festnetz). */
            kommunikationsmittel?: string | null;
            /** Format: double */
            lat?: number | null;
            /** Format: double */
            lon?: number | null;
            material_mitglieder: components["schemas"]["EinheitMitgliedMaterial"][];
            name: string;
            personal_mitglieder: components["schemas"]["EinheitMitgliedPerson"][];
            soll?: null | components["schemas"]["Staerke"];
            /** Format: int64 */
            sortier: number;
            sprechgruppen: components["schemas"]["SprechgruppeAnzeige"][];
            /** Format: int64 */
            typ_id?: number | null;
            typ_label?: string | null;
            tz_fachaufgabe?: string | null;
            tz_organisation?: string | null;
            /** Format: int64 */
            ueber_einheit_id?: number | null;
        };
        /** @description Fahrzeug-Mitglied einer Einheit (leichtgewichtig). */
        EinheitMitgliedFahrzeug: {
            /**
             * Format: int64
             * @description `einsatz_fahrzeug.id` der Dispozeile.
             */
            ef_id: number;
            fahrzeugtyp?: string | null;
            funkrufname: string;
        };
        /** @description Material-Mitglied einer Einheit (leichtgewichtig). */
        EinheitMitgliedMaterial: {
            bezeichnung: string;
            /**
             * Format: int64
             * @description `einsatz_material.id` der Dispozeile.
             */
            em_id: number;
            /** Format: int64 */
            menge: number;
            /** @description Festes Status-Enum als String (z. B. "einsatzbereit"). */
            status: components["schemas"]["MaterialStatus"];
        };
        /** @description Personal-Mitglied einer Einheit (leichtgewichtig für die Einheiten-Anzeige). */
        EinheitMitgliedPerson: {
            /**
             * Format: int64
             * @description `einsatz_personal.id` der Dispozeile.
             */
            ep_id: number;
            funktion?: string | null;
            /** @description `true`, wenn diese Person als Führer der Einheit eingetragen ist. */
            ist_fuehrer: boolean;
            name: string;
            staerke_position?: null | components["schemas"]["StaerkePosition"];
        };
        /**
         * @description Einheitstyp-Katalog-Eintrag (org-weit), inkl. aufgelöster optionaler Soll-Stärke.
         *     `aktiv` wird nicht serialisiert (Listen-Endpunkt liefert ohnehin nur aktive).
         */
        EinheitTyp: {
            /** Format: int64 */
            id: number;
            label: string;
            soll?: null | components["schemas"]["Staerke"];
            /** Format: int64 */
            sortier: number;
        };
        /**
         * @description Einheiten-System (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `einheiten_system`.
         * @enum {string}
         */
        EinheitenSystem: "metrisch" | "imperial";
        /**
         * @description Öffentliche Einsatz-Darstellung für API-Antworten,
         *     inklusive Org-Angaben und der Rolle des abfragenden Benutzers.
         */
        EinsatzAnzeige: {
            abgeschlossen_at?: string | null;
            /** Format: int64 */
            abgeschlossen_von?: number | null;
            angelegt_at: string;
            /** Format: int64 */
            anzahl_betroffene_initial?: number | null;
            begonnen_at: string;
            bezeichnung: string;
            einsatzart: components["schemas"]["Einsatzart"];
            einsatznummer_intern?: string | null;
            einsatzort?: string | null;
            /** Format: double */
            einsatzort_lat?: number | null;
            /** Format: double */
            einsatzort_lon?: number | null;
            /** Format: int64 */
            id: number;
            leitstellen_nr?: string | null;
            meine_rolle?: null | components["schemas"]["EinsatzRolle"];
            meldende_stelle?: string | null;
            /** Format: int64 */
            org_id: number;
            org_name: string;
            /** @description Aufbewahrungsfrist (LFH-130); `None` = keine Frist gesetzt. */
            retention_bis?: string | null;
            sachverhalt?: string | null;
            status: components["schemas"]["EinsatzStatus"];
            stichwort?: string | null;
        };
        /**
         * @description Aufgelöste Dispositions-Anzeige: Identität nach der Auflösungsregel
         *     (Live aus dem Stamm bei aktivem Einsatz + Fahrzeug in Dienst, sonst Snapshot)
         *     plus aufgelöster Status.
         */
        EinsatzFahrzeugAnzeige: {
            /**
             * Format: int64
             * @description BR‑1: aktuell bereitgestellter Bereitstellungsraum (NULL = in keinem BR).
             */
            aktueller_br_id?: number | null;
            bemerkung?: string | null;
            disponiert_at: string;
            /** Format: int64 */
            disponiert_von?: number | null;
            /**
             * Format: int64
             * @description Zugeordnete Einheit (K&M‑3); `None` = freie, nicht zugeordnete Kraft.
             */
            einheit_id?: number | null;
            /** Format: int64 */
            einsatz_id: number;
            /**
             * Format: int64
             * @description `None` = Ad-hoc-externes Fahrzeug (kein Stamm-Bezug).
             */
            fahrzeug_id?: number | null;
            fahrzeugtyp?: string | null;
            funkrufname: string;
            /** Format: int64 */
            id: number;
            ist_adhoc: boolean;
            kennzeichen?: string | null;
            /** Format: double */
            lat?: number | null;
            /** Format: double */
            lon?: number | null;
            opta?: string | null;
            soll_besatzung?: null | components["schemas"]["Staerke"];
            status_farbe?: string | null;
            /** Format: int64 */
            status_id?: number | null;
            status_kategorie?: null | components["schemas"]["StatusKategorie"];
            status_label?: string | null;
            traegerorganisation?: string | null;
            tz_fachaufgabe?: string | null;
            tz_organisation?: string | null;
        };
        /**
         * @description Aufgelöste Material-Dispositionszeile: Identität nach der Auflösungsregel
         *     (Live aus dem Stamm bei aktivem Einsatz + Material in Dienst, sonst Snapshot);
         *     `menge` und `status` kommen **immer** aus der Dispositionszeile.
         */
        EinsatzMaterialAnzeige: {
            bemerkung?: string | null;
            bestandsnummer?: string | null;
            bezeichnung: string;
            disponiert_at: string;
            /** Format: int64 */
            disponiert_von?: number | null;
            /**
             * Format: int64
             * @description Zugeordnete Einheit; `None` = freie, nicht zugeordnete Position.
             */
            einheit_id?: number | null;
            /** Format: int64 */
            einsatz_id: number;
            /** Format: int64 */
            id: number;
            ist_adhoc: boolean;
            kategorie?: string | null;
            /**
             * Format: int64
             * @description `None` = Ad-hoc-externes Material (kein Stamm-Bezug).
             */
            material_id?: number | null;
            /** Format: int64 */
            menge: number;
            status: components["schemas"]["MaterialStatus"];
            traegerorganisation?: string | null;
            /**
             * Format: int64
             * @description Zugeordnete Unfallhilfsstelle; `None` = nicht einer UHS zugeordnet.
             */
            uhs_id?: number | null;
        };
        /**
         * @description Override-Zeile wie in der DB abgelegt. `sichtbar` aus INTEGER (0/1) dekodiert;
         *     `benoetigte_rolle` ist `None` (= frei) oder ein gültiger Rollen-String.
         */
        EinsatzModulOverride: {
            benoetigte_rolle?: string | null;
            /** Format: int64 */
            einsatz_id: number;
            geaendert_at?: string | null;
            /** Format: int64 */
            geaendert_von?: number | null;
            modul_key: string;
            sichtbar: boolean;
        };
        /**
         * @description Aufgelöste Dispositions-Anzeige: Identität nach der Auflösungsregel (Live aus dem
         *     Stamm bei aktivem Einsatz + Person in Dienst, sonst Snapshot), aufgelöste
         *     Stärke-Position (Dispo-Override vor Stamm-Default) und aufgelöster Status.
         */
        EinsatzPersonalAnzeige: {
            bemerkung?: string | null;
            disponiert_at: string;
            /** Format: int64 */
            disponiert_von?: number | null;
            /**
             * Format: int64
             * @description Zugeordnete Einheit (K&M‑3); `None` = freie, nicht zugeordnete Kraft.
             */
            einheit_id?: number | null;
            /** Format: int64 */
            einsatz_id: number;
            /**
             * Format: int64
             * @description Fahrzeug, dessen Besatzung die Kraft ist (LFH-9); `None` = keinem Fahrzeug zugeteilt.
             *     Unabhängig von `einheit_id` (orthogonale Zuordnung).
             */
            fahrzeug_id?: number | null;
            /** @description Qualifikationen/Funktion als flacher Text (Live recomposed oder Snapshot). */
            funktion?: string | null;
            /** Format: int64 */
            id: number;
            ist_adhoc: boolean;
            name: string;
            /**
             * Format: int64
             * @description `None` = Ad-hoc-externe Person (kein Stamm-Bezug).
             */
            personal_id?: number | null;
            staerke_position?: null | components["schemas"]["StaerkePosition"];
            status_farbe?: string | null;
            /** Format: int64 */
            status_id?: number | null;
            status_kategorie?: null | components["schemas"]["StatusKategorie"];
            status_label?: string | null;
            traegerorganisation?: string | null;
        };
        /**
         * @description Rolle einer Person innerhalb eines konkreten Einsatzes.
         *     Wird als TEXT in der DB gespeichert und manuell konvertiert (kein sqlx-Enum-Decode).
         * @enum {string}
         */
        EinsatzRolle: "einsatzleitung" | "fuehrungspersonal" | "beobachter";
        /**
         * @description Einsatz-Status (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `status`.
         * @enum {string}
         */
        EinsatzStatus: "aktiv" | "abgeschlossen";
        /**
         * @description Aufgelöste Abschnitts-Anzeige (flach; der Baum wird im FE über
         *     `ueber_abschnitt_id` gebaut), inkl. aufgelöstem Leiter-Namen.
         */
        EinsatzabschnittAnzeige: {
            bemerkung?: string | null;
            /** Format: int64 */
            einsatz_id: number;
            erreichbarkeit?: string | null;
            flaeche_geojson?: string | null;
            /** Format: int64 */
            id: number;
            kommunikationsmittel?: string | null;
            /** Format: int64 */
            leiter_id?: number | null;
            /** @description Name der disponierten Leiter-Person (aufgelöst), falls gesetzt. */
            leiter_name?: string | null;
            name: string;
            /** Format: int64 */
            sortier: number;
            /** @description Historischer Freitext-Wert (eingefroren; nicht mehr schreibbar). */
            sprechgruppe_dmo?: string | null;
            /** @description Historischer Freitext-Wert (eingefroren; nicht mehr schreibbar). */
            sprechgruppe_tmo?: string | null;
            /** @description Zugeordnete Sprechgruppen (aus Katalogeintrag oder einsatz-lokal). */
            sprechgruppen: components["schemas"]["SprechgruppeAnzeige"][];
            tz_fachaufgabe?: string | null;
            tz_organisation?: string | null;
            /** Format: int64 */
            ueber_abschnitt_id?: number | null;
        };
        /**
         * @description Einsatzart (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `einsatzart`.
         * @enum {string}
         */
        Einsatzart: "realeinsatz" | "uebung" | "sanitaetsdienst" | "bereitstellung";
        /** @description API-Darstellung der Einstellungen (`fachebenen_sichtbar` als Objekt). */
        EinstellungenAnzeige: {
            auftrag_nummer_eingefroren: boolean;
            auftrag_nummer_praefix?: string | null;
            /** Format: int64 */
            auftrag_nummer_start?: number | null;
            /** Format: int64 */
            auftrag_quittierung_frist_min?: number | null;
            /** Format: int64 */
            auto_etb_eintraege?: number | null;
            basemap_modus?: null | components["schemas"]["BasemapModus"];
            einheiten?: null | components["schemas"]["EinheitenSystem"];
            /** Format: int64 */
            einsatz_id: number;
            /**
             * @description Freeze pro Nummernkreis (LFH-133): true, sobald die erste Nummer vergeben ist
             *     (Präfix + Startwert dann read-only). Aus Daten-Existenz abgeleitet, nicht gespeichert.
             */
            etb_nummer_eingefroren: boolean;
            etb_nummer_praefix?: string | null;
            /** Format: int64 */
            etb_nummer_start?: number | null;
            fachebenen_sichtbar?: unknown;
            geaendert_at?: string | null;
            /** Format: int64 */
            geaendert_von?: number | null;
            /** Format: double */
            karten_zoom_start?: number | null;
            koordinatenformat?: null | components["schemas"]["Koordinatenformat"];
            /** Format: int64 */
            meldung_bestaetigung_frist_min?: number | null;
            meldung_nummer_eingefroren: boolean;
            meldung_nummer_praefix?: string | null;
            /** Format: int64 */
            meldung_nummer_start?: number | null;
            /**
             * Format: int64
             * @description Aufbewahrungs-Dauer-Politik in Tagen (LFH-135); `None` = keine Auto-Frist.
             */
            retention_dauer_tage?: number | null;
            standard_modul?: string | null;
            zeitformat?: null | components["schemas"]["Zeitformat"];
            zeitzone?: string | null;
        };
        /**
         * @description Antwort-Shape von `einstellungen_laden`: rohe Einsatz-Override-Werte (geflacht)
         *     plus org-weite Defaults als eingebettetes Objekt (ohne Audit-Felder).
         */
        EinstellungenMitOrgDefaults: components["schemas"]["EinstellungenAnzeige"] & {
            org_defaults: components["schemas"]["OrgEinstellungenHinweis"];
        };
        /**
         * @description Empfänger-Diskriminator eines Auftrags (Schema-Anker für die OpenAPI-Union, LFH-120).
         *     Wire == `empfaenger_typ`.
         * @enum {string}
         */
        EmpfaengerTyp: "abschnitt" | "einheit" | "funktion" | "person" | "fahrzeug" | "extern";
        /**
         * @description Öffentliche Darstellung einer Erinnerung. `ist_faellig` wird pro Read aus
         *     `faellig_at <= jetzt` berechnet (nicht persistiert) — die Fälligkeit ist
         *     damit unabhängig davon korrekt, ob/wann der Scheduler-Tick lief.
         */
        ErinnerungAnzeige: {
            beschreibung?: string | null;
            /** Format: int64 */
            bezug_id?: number | null;
            bezug_typ?: string | null;
            /** Format: int64 */
            einsatz_id: number;
            empfaenger_funktion?: string | null;
            erledigt_at?: string | null;
            erstellt_at: string;
            /** Format: int64 */
            erstellt_von_id: number;
            faellig_at: string;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            intervall_minuten?: number | null;
            /** @description Abgeleitet: `faellig_at <= jetzt` zum Zeitpunkt der Abfrage. */
            ist_faellig: boolean;
            quelle: string;
            quittiert_at?: string | null;
            /** Format: int64 */
            quittiert_von_id?: number | null;
            status: components["schemas"]["ErinnerungStatus"];
            titel: string;
            vollzogen_at?: string | null;
            /** Format: int64 */
            vollzogen_von_id?: number | null;
            vollzug_status: string;
        };
        /**
         * @description LFH-120: Schema-Anker für die `status`-Union (geschlossenes Code-Vokabular, s. STATUS_*).
         * @enum {string}
         */
        ErinnerungStatus: "offen" | "erledigt" | "quittiert";
        /**
         * @description Öffentliche Sicht eines ETB-Baustein-Katalogeintrags. Die DB-Spalten `aktiv`,
         *     `erstellt_at` und `aktualisiert_at` werden bewusst nicht serialisiert.
         */
        EtbBaustein: {
            /** Format: int64 */
            id: number;
            inhalt: string;
            label: string;
            meldeweg?: null | components["schemas"]["MeldeWeg"];
            /** Format: int64 */
            sortier: number;
            typ: components["schemas"]["EtbTyp"];
            veranlassung?: string | null;
        };
        /**
         * @description Öffentliche Darstellung eines ETB-Eintrags für API-Antworten und SSE.
         *     `erfasser_name` ist der Anzeigename des Erfassers (per JOIN ermittelt).
         */
        EtbEintragAnzeige: {
            an?: string | null;
            /**
             * Format: int64
             * @description Rückverweis auf den auslösenden Auftrag (LFH-52), falls aus Auftrag/Vollzug erzeugt.
             */
            auftrag_id?: number | null;
            /**
             * Format: int64
             * @description Gesetzt, wenn dieser Eintrag der Freigabe-Snapshot eines Befehls ist (LFH-64). Sonst `None`.
             */
            befehl_id?: number | null;
            /** Format: int64 */
            berichtigt_eintrag_id?: number | null;
            ereigniszeit: string;
            /** Format: int64 */
            erfasser_id: number;
            erfasser_name: string;
            erfasst_lokal_at?: string | null;
            /** Format: int64 */
            id: number;
            inhalt: string;
            /**
             * Format: int64
             * @description Gesetzt, wenn dieser Eintrag der Freigabe-Snapshot eines Lageberichts ist
             *     (Timeline-Badge + Rückverlinkung). Sonst `None`.
             */
            lagebericht_id?: number | null;
            /** Format: int64 */
            lfd_nr: number;
            meldeweg?: null | components["schemas"]["MeldeWeg"];
            received_at: string;
            typ: components["schemas"]["EtbTyp"];
            veranlassung?: string | null;
            von?: string | null;
        };
        /**
         * @description Eintragstyp eines ETB-Eintrags. Wird als TEXT in der DB gespeichert.
         * @enum {string}
         */
        EtbTyp: "meldung" | "anordnung" | "lage" | "entscheidung" | "system" | "berichtigung";
        /** @description Einheitlicher Umschlag für jede Fachebene. */
        FachebeneAntwort: {
            attribution: string;
            /**
             * @description GeoJSON FeatureCollection. Laufzeittyp bleibt `Value` (die Normalisierer bauen sie per
             *     `json!`); `GeoJsonFeatureCollection` ist der Schema-Anker (LFH-265), belegt durch die
             *     `from_value`-Tests in `karte::normalisierung`.
             */
            features: components["schemas"]["GeoJsonFeatureCollection"];
            quelle: string;
            stand?: string | null;
            status: components["schemas"]["FachebeneStatus"];
        };
        /**
         * @description Status einer Fachebenen-Antwort.
         * @enum {string}
         */
        FachebeneStatus: "ok" | "leer" | "offline";
        /** @description Öffentliche Fahrzeug-Darstellung (ohne `org_id`). */
        FahrzeugAnzeige: {
            angelegt_at: string;
            bemerkung?: string | null;
            dienststatus: components["schemas"]["Dienststatus"];
            fahrzeugtyp?: string | null;
            fms_issi?: string | null;
            funkrufname: string;
            /** Format: int64 */
            id: number;
            kennzeichen?: string | null;
            opta?: string | null;
            sondersignal: boolean;
            staerke?: null | components["schemas"]["Staerke"];
            standort?: string | null;
            traegerorganisation?: string | null;
            /** Format: int64 */
            tragenkapazitaet?: number | null;
        };
        /**
         * @description Status-Katalog-Eintrag (org-weit). `aktiv` wird nicht serialisiert
         *     (Listen-Endpunkt liefert ohnehin nur aktive).
         */
        FahrzeugStatus: {
            farbe?: string | null;
            /** Format: int64 */
            fms_anker?: number | null;
            /** Format: int64 */
            id: number;
            kategorie: components["schemas"]["StatusKategorie"];
            label: string;
            /** Format: int64 */
            sortier: number;
        };
        /**
         * @description Abgeleitete AutoComplete-Vorschläge für die Stamm-Felder (DISTINCT, org-weit).
         *     Speist die Comboboxen im Fahrzeug-Formular mit bereits verwendeten Werten.
         */
        FahrzeugVorschlaege: {
            fahrzeugtyp: string[];
            standort: string[];
            traegerorganisation: string[];
        };
        /** @description Ein freies taktisches Zeichen (Punkt-Marker ohne Fachobjekt, LFH-170). */
        FreiesZeichenAnzeige: {
            /**
             * Format: int64
             * @description Ansichts-Zugehörigkeit (LFH-320): `None` = auf allen Ansichten sichtbar.
             */
            ansicht_id?: number | null;
            einheit?: string | null;
            /** Format: int64 */
            einsatz_id: number;
            erstellt_at: string;
            /** Format: int64 */
            erstellt_von: number;
            fachaufgabe?: string | null;
            farbe?: string | null;
            funktion?: string | null;
            geaendert_at: string;
            grundzeichen: string;
            /** Format: int64 */
            id: number;
            label?: string | null;
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
            organisation?: string | null;
            symbol?: string | null;
        };
        /** @description Schlanke Karten-Sicht einer Führungskraft (Einheits- oder Abschnittsführung). */
        FuehrungskraftKarte: {
            /** Format: int64 */
            einsatz_id: number;
            /**
             * @description Qualifikationen/Funktion als flacher Text (Snapshot). Quelle für die FE-Ableitung der
             *     Fachaufgabe des Personen-Zeichens (LFH-172); `tz_fachaufgabe` bleibt vorrangig.
             */
            funktion?: string | null;
            /** Format: int64 */
            id: number;
            ist_abschnittsleiter: boolean;
            ist_einheitsfuehrer: boolean;
            /** Format: double */
            lat?: number | null;
            /** Format: double */
            lon?: number | null;
            name: string;
            tz_fachaufgabe?: string | null;
            tz_organisation?: string | null;
        };
        /**
         * @description Aufgelöste Matrix-Zelle (gefahrengebiet-skopiert). Die Liste enthält nur Zellen mit
         *     `warnstufe != 'keine'`; das Frontend rendert das 13×5-Raster aus den Katalogen.
         */
        GefahrBewertungAnzeige: {
            /** Format: int64 */
            aktualisiert_von: number;
            beschreibung?: string | null;
            erstellt_at: string;
            geaendert_at: string;
            /** Format: int64 */
            gefahrengebiet_id: number;
            gefahrentyp: components["schemas"]["Gefahrentyp"];
            gemeldet_von?: string | null;
            /** Format: int64 */
            id: number;
            schutzobjekt: components["schemas"]["Schutzobjekt"];
            warnstufe: components["schemas"]["Warnstufe"];
        };
        /**
         * @description Ein Gefahrengebiet (Gruppe aus 1..n gefahrengebiet-Zonen), trägt eine Matrix.
         *     `zonen_ids`: zugehörige lage_zone-IDs. `hoechste_warnstufe`: stärkste gesetzte
         *     Zelle der Matrix (Severity-Maximum), `keine` wenn nichts gesetzt.
         */
        GefahrengebietAnzeige: {
            /** Format: int64 */
            einsatz_id: number;
            hoechste_warnstufe: components["schemas"]["Warnstufe"];
            /** Format: int64 */
            id: number;
            label?: string | null;
            zonen_ids: number[];
        };
        /**
         * @description Gefahrentyp (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `gefahrentyp`.
         * @enum {string}
         */
        Gefahrentyp: "atemgifte" | "angstreaktion" | "ausbreitung" | "atomare_strahlung" | "chemische_stoffe" | "erkrankung_verletzung" | "explosion" | "elektrizitaet" | "einsturz" | "absturz" | "brand" | "durchbruch" | "ertrinken";
        /**
         * @description Ein GeoJSON-Feature. `geometry` ist optional (NINA liefert Einträge ohne Geometrie),
         *     `properties` sind flache Skalar-Properties (MapLibre stringifiziert Verschachteltes).
         */
        GeoJsonFeature: {
            geometry?: null | components["schemas"]["GeoJsonGeometrie"];
            properties: {
                [key: string]: unknown;
            };
            type: string;
        };
        /** @description Eine GeoJSON-FeatureCollection — der Schema-Anker für `FachebeneAntwort.features`. */
        GeoJsonFeatureCollection: {
            features: components["schemas"]["GeoJsonFeature"][];
            type: string;
        };
        /**
         * @description Geometrie eines GeoJSON-Features. Bewusst FLACH gehalten (LFH-265): `typ` bleibt `String`
         *     statt Literal-Enum (spart zwei weitere ToSchema-Enums samt Wire-Pins und bricht keinen
         *     Konsumenten), `coordinates` bleibt `Value` (Punkt/Linie/Polygon haben unterschiedliche Tiefe).
         *     Zweck ist Nicht-Regression: ohne diesen Anker generiert utoipa für `FachebeneAntwort.features`
         *     ein typloses Schema (`unknown` im Frontend).
         */
        GeoJsonGeometrie: {
            coordinates: unknown;
            type: string;
        };
        /**
         * @description Optionale Geschlechtsangabe. `unbekannt` ist ein erstklassiger Wert.
         * @enum {string}
         */
        Geschlecht: "maennlich" | "weiblich" | "divers" | "unbekannt";
        /** @description Anzeige-DTO (ohne BLOB-Bytes). `sichtbar` als bool für saubere JSON-Ausgabe. */
        HintergrundbildAnzeige: {
            /**
             * Format: int64
             * @description Ansichts-Zugehörigkeit (LFH-320): `None` = auf allen Ansichten sichtbar.
             */
            ansicht_id?: number | null;
            ecken_json: string;
            /** Format: int64 */
            einsatz_id: number;
            erstellt_at: string;
            geaendert_at: string;
            /** Format: int64 */
            groesse: number;
            /** Format: int64 */
            hochgeladen_von: number;
            /** Format: int64 */
            id: number;
            mime: string;
            name: string;
            /** Format: int64 */
            opazitaet: number;
            /** Format: int64 */
            reihenfolge: number;
            sichtbar: boolean;
        };
        /**
         * @description Antwort von `GET /api/karte/config`. Liefert NUR, was die Karte zur Laufzeit braucht —
         *     NICHT den Server-Dateipfad der Offline-Kartendatei. Shape ist eingefroren (Frontend-Vertrag,
         *     `frontend/src/api/karte.ts`); nur die Datenquelle wechselte von ENV/Extension auf die DB.
         */
        KarteConfigAntwort: {
            /**
             * @description True, wenn der zentrale karten-service konfiguriert ist (URL+Token) → Admin darf Region-Builds
             *     anstoßen. Steuert die Sichtbarkeit der Bau-UI (LFH-203). Reine Verfügbarkeit, kein Secret.
             */
            karten_bau_verfuegbar: boolean;
            /** @description Pflicht-Attribution der ersten sichtbaren Region (Kompat). `None`, wenn keine Region bereit. */
            offline_attribution?: string | null;
            offline_format?: null | components["schemas"]["OnlineStyleTyp"];
            /**
             * @description Alle gemeinsam anzuzeigenden Offline-Regionen (LFH-188): die Offline-Karte ist die
             *     VEREINIGUNG aller bereiten Regionen, je Region eine eigene Vector-Source. Leere Liste =
             *     keine Region bereit (= `offline_verfuegbar = false`).
             */
            offline_regionen: components["schemas"]["OfflineRegionConfig"][];
            /**
             * @description Tile-Endpoint-Template der ERSTEN sichtbaren Offline-Region inkl. Cache-Bust `?v=<token>`.
             *     **Kompat-Feld** (LFH-188): die eigentliche Quelle der Wahrheit ist `offline_regionen`; alte
             *     Clients ohne Multi-Region-Support degradieren auf diese eine Region. Der Token wechselt bei
             *     Karten-Swap, sonst cacht MapLibre den alten Tile-Aufbau unter gleicher URL → korrupte Tiles.
             */
            offline_tiles_url?: string | null;
            offline_verfuegbar: boolean;
            online_styles: components["schemas"]["OnlineStyle"][];
        };
        /**
         * @description Eine Kartenansicht wie ans Frontend geliefert. Enum-tragende `String`-Felder
         *     tragen `#[schema(value_type = Option<Enum>)]`, damit die generierte TS die Union
         *     kennt; `Option<T>` mit `skip_serializing_if`, damit absent/null unterscheidbar
         *     bleibt (Norm ab LFH-265). `layer_sichtbar`/`fachebenen_sichtbar` sind opake JSON.
         */
        KartenAnsichtAnzeige: {
            basemap_modus?: null | components["schemas"]["BasemapModus"];
            /** Format: int64 */
            einsatz_id: number;
            erstellt_at: string;
            /** Format: int64 */
            erstellt_von?: number | null;
            fachebenen_sichtbar?: unknown;
            geaendert_at: string;
            /** Format: int64 */
            geaendert_von?: number | null;
            /** Format: int64 */
            id: number;
            ist_standard: boolean;
            karten_theme?: null | components["schemas"]["KartenTheme"];
            layer_sichtbar?: unknown;
            name: string;
            online_stil?: string | null;
            /** Format: int64 */
            reihenfolge: number;
            /** Format: double */
            zentrum_lat?: number | null;
            /** Format: double */
            zentrum_lon?: number | null;
            /** Format: double */
            zoom?: number | null;
        };
        /**
         * @description Karten-Theme (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `karten_theme`.
         * @enum {string}
         */
        KartenTheme: "auto" | "light" | "dark";
        /**
         * @description Koordinatenformat (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `koordinatenformat`.
         * @enum {string}
         */
        Koordinatenformat: "wgs84" | "dms" | "utm" | "mgrs" | "gk";
        /**
         * @description Lageobjekt aus lagerelevanter Meldung (LFH-95). Herkunfts-Felder (meldung_*)
         *     per JOIN — am Lageobjekt bleibt die Quell-Meldung nachvollziehbar.
         */
        LageMeldungAnzeige: {
            /** Format: int64 */
            einsatz_id: number;
            erstellt_at: string;
            /** Format: int64 */
            erstellt_von_id: number;
            /** Format: int64 */
            id: number;
            /** Format: double */
            lat?: number | null;
            /** Format: double */
            lon?: number | null;
            meldung_absender: string;
            /** Format: int64 */
            meldung_id: number;
            /** Format: int64 */
            meldung_lfd_nr: number;
            text: string;
        };
        /**
         * @description Metadaten eines Snapshots — **ohne** das `daten`-Dokument (Listen-Response; `daten` kann
         *     je Stand ~100 KB groß sein und gehört nicht in die Liste).
         */
        LageSnapshotAnzeige: {
            bezeichnung?: string | null;
            /** Format: int64 */
            einsatz_id: number;
            erstellt_at: string;
            /** Format: int64 */
            erstellt_von: number;
            /** Format: int64 */
            id: number;
            notiz?: string | null;
            /** Format: int64 */
            schema_version: number;
            stand_at: string;
        };
        /** @description Volldokument eines Snapshots inkl. eingefrorenem Lagebild (`daten`) — Einzel-Response. */
        LageSnapshotDokument: {
            bezeichnung?: string | null;
            /** @description Eingefrorenes Lagebild (rohe `*Anzeige`-DTO-Listen, `schema_version = 1`). */
            daten: unknown;
            /** Format: int64 */
            einsatz_id: number;
            erstellt_at: string;
            /** Format: int64 */
            erstellt_von: number;
            /** Format: int64 */
            id: number;
            notiz?: string | null;
            /** Format: int64 */
            schema_version: number;
            stand_at: string;
        };
        /** @description Eine freie Lage-Zone (Gefahren-/Absperrzone). Eigenständige Entität — kein Fachobjekt. */
        LageZoneAnzeige: {
            /**
             * Format: int64
             * @description Ansichts-Zugehörigkeit (LFH-320): `None` = auf allen Ansichten sichtbar.
             */
            ansicht_id?: number | null;
            /** Format: int64 */
            einsatz_id: number;
            erstellt_at: string;
            /** Format: int64 */
            erstellt_von: number;
            farbe?: string | null;
            geaendert_at: string;
            /** Format: int64 */
            gefahrengebiet_id?: number | null;
            geometrie: string;
            geometrie_typ: string;
            /** Format: int64 */
            id: number;
            label?: string | null;
            notiz?: string | null;
            typ: components["schemas"]["LageZoneTyp"];
        };
        /**
         * @description Zonen-Typ (Schema-Anker für die OpenAPI-Union, LFH-120; TS: `ZoneTyp`). Wire == `typ`.
         * @enum {string}
         */
        LageZoneTyp: "gefahrengebiet" | "absperrbereich" | "absperrgrenze" | "sperrgebiet" | "freie_skizze";
        /** @description Ein gefüllter Abschnitt (so persistiert als JSON-Array-Element). */
        LageberichtAbschnitt: {
            schluessel: string;
            text: string;
        };
        /** @description Öffentliche Anzeige eines Lageberichts (Abschnitte aus JSON geparst, Namen aufgelöst). */
        LageberichtAnzeige: {
            abschnitte: components["schemas"]["LageberichtAbschnitt"][];
            aktualisiert_at: string;
            /** Format: int64 */
            einsatz_id: number;
            /** Format: int64 */
            ersteller_id: number;
            ersteller_name: string;
            erstellt_at: string;
            /** Format: int64 */
            etb_eintrag_id?: number | null;
            freigegeben_at?: string | null;
            /** Format: int64 */
            freigegeben_von_id?: number | null;
            freigegeben_von_name?: string | null;
            /** Format: int64 */
            id: number;
            status: components["schemas"]["LageberichtStatus"];
            titel: string;
            /** Format: int64 */
            version: number;
            /** Format: int64 */
            vorgaenger_id?: number | null;
            vorlage: components["schemas"]["LageberichtVorlage"];
            zeitstand: string;
        };
        /**
         * @description Lagebericht-Status (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `status`.
         * @enum {string}
         */
        LageberichtStatus: "entwurf" | "freigegeben";
        /**
         * @description Lagebericht-Vorlage (Schema-Anker für die OpenAPI-Union, LFH-120; TS: `LageberichtVorlageKey`).
         *     Wire == `vorlage`.
         * @enum {string}
         */
        LageberichtVorlage: "lagebericht" | "lagebeurteilung" | "freitext";
        /**
         * @description SSE-Wire-Event-Namen als BE↔FE-Kontrakt (LFH-298). Schema-Anker für die OpenAPI-Union;
         *     die Emitter routen über `as_str()`, das Frontend filtert exakt auf diese Wire-Tags.
         * @enum {string}
         */
        LiveEvent: "uhs" | "schaden" | "fahrzeug" | "material" | "tier" | "lage_zone" | "freies_zeichen" | "gefahr" | "einheit" | "abschnitt" | "person" | "personal" | "lagebericht" | "chat" | "erinnerung" | "auftrag" | "nachforderung" | "meldung" | "bereitstellungsraum" | "karte_bild" | "etb" | "befehl" | "karten_ansicht" | "lage_snapshot" | "sofortmeldung" | "lagged";
        /** @description Öffentliche Material-Darstellung (ohne `org_id`). */
        MaterialAnzeige: {
            angelegt_at: string;
            bemerkung?: string | null;
            bestandsnummer?: string | null;
            bezeichnung: string;
            dienststatus: components["schemas"]["Dienststatus"];
            /** Format: int64 */
            id: number;
            kategorie?: string | null;
            standort?: string | null;
            traegerorganisation?: string | null;
        };
        /**
         * @description Fester Status einer Material-Dispositionszeile (kein admin-pflegbarer Katalog).
         *     Als TEXT in der DB gespeichert; manuell konvertiert (analog `StaerkePosition`).
         * @enum {string}
         */
        MaterialStatus: "einsatzbereit" | "im_einsatz" | "defekt" | "verbraucht" | "desinfektion_noetig";
        /**
         * @description Meldeweg eines Eintrags (optional).
         * @enum {string}
         */
        MeldeWeg: "funk" | "telefon" | "persoenlich" | "sonstige";
        /**
         * @description Anzeige einer Meldung inkl. abgeleiteter Felder (Bearbeitername per JOIN,
         *     `lage_meldung_id` als Herkunfts-Rückverweis, `ist_offen` für Posteingang-Filter).
         */
        MeldungAnzeige: {
            absender: string;
            /** Format: int64 */
            auftrag_id?: number | null;
            /** Format: int64 */
            bearbeiter_id?: number | null;
            bearbeiter_name?: string | null;
            /** @description Abgeleitet (kommunikation_status, Quittungs-Achse): Bestätigt-um. */
            bestaetigt_at?: string | null;
            /**
             * Format: int64
             * @description Abgeleitet: Bestätigt-von (Benutzer-id).
             */
            bestaetigt_von_id?: number | null;
            /** @description Abgeleitet: Bestätigt-von (Anzeigename, JOIN benutzer). */
            bestaetigt_von_name?: string | null;
            /** @description Absolute Bestätigungsfrist (UTC), NULL wenn keine Pflicht. */
            bestaetigung_frist_at?: string | null;
            /** @description Sofortmeldung & Eskalation (LFH-85/97): aktive Bestätigungspflicht. */
            bestaetigung_pflicht: boolean;
            eingang_at: string;
            /** Format: int64 */
            einsatz_id: number;
            empfaenger?: string | null;
            ereigniszeit: string;
            /** Format: int64 */
            erfasst_von_id: number;
            /**
             * @description Erledigt-Zeitpunkt (UTC), first-write-wins beim Übergang nach 'erledigt' (LFH-113);
             *     NULL solange nie erledigt. Bleibt erhalten, falls der Status später zurückgesetzt wird.
             */
            erledigt_at?: string | null;
            erstellt_at: string;
            /** @description Frist überschritten + unbestätigt (vom Erinnerungs-Tick gesetzt, Re-Highlight). */
            eskaliert: boolean;
            /** Format: int64 */
            etb_meldung_id?: number | null;
            /** Format: int64 */
            id: number;
            inhalt: string;
            /** @description Abgeleitet: quittiert_at IS NOT NULL. */
            ist_bestaetigt: boolean;
            /** @description Abgeleitet: status != 'erledigt' (Posteingang = offene Meldungen). */
            ist_offen: boolean;
            /** @description Abgeleitet: pflichtig, unbestätigt und Frist <= jetzt. */
            ist_ueberfaellig: boolean;
            /**
             * Format: int64
             * @description Abgeleitet: id des erzeugten Lageobjekts (LFH-95), falls übergeben.
             */
            lage_meldung_id?: number | null;
            lagerelevant: boolean;
            /** Format: int64 */
            lfd_nr: number;
            meldeweg: components["schemas"]["MeldeWeg"];
            meldungsart: components["schemas"]["Meldungsart"];
            prioritaet: components["schemas"]["Prioritaet"];
            /** @description Richtung intern/extern (LFH-87). */
            richtung: components["schemas"]["Richtung"];
            status: components["schemas"]["MeldungStatus"];
        };
        /**
         * @description Triage-Status einer Meldung (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `status`.
         * @enum {string}
         */
        MeldungStatus: "neu" | "gesichtet" | "in_bearbeitung" | "erledigt";
        /**
         * @description Meldungsart (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `meldungsart`.
         * @enum {string}
         */
        Meldungsart: "lagemeldung" | "sofortmeldung" | "rueckmeldung" | "vollzugsmeldung" | "anfrage" | "sonstige";
        /** @description Mitglied eines Einsatzes für API-Antworten (mit Benutzer-Klartext, ohne Hash). */
        MitgliedAnzeige: {
            anzeigename: string;
            /** Format: int64 */
            benutzer_id: number;
            benutzername: string;
            einsatz_rolle: components["schemas"]["EinsatzRolle"];
            zugewiesen_at: string;
        };
        /**
         * @description Anzeige einer Nachforderung inkl. Ersteller-Name (JOIN) und abgeleitetem `ist_offen`
         *     (noch nicht eingetroffen/abgelehnt). Reihenfolge der Felder = SELECT-Projektion.
         */
        NachforderungAnzeige: {
            abgelehnt_at?: string | null;
            abgelehnt_grund?: string | null;
            adressat_bezeichnung?: string | null;
            adressat_kategorie: components["schemas"]["AdressatKategorie"];
            angefordert_at: string;
            /** Format: int64 */
            anzahl?: number | null;
            art: string;
            begruendung?: string | null;
            bezeichnung: string;
            eingetroffen_at?: string | null;
            /** Format: int64 */
            einsatz_id: number;
            erstellt_at: string;
            /** Format: int64 */
            erstellt_von_id: number;
            /** @description Abgeleitet: Ersteller-Anzeigename (LEFT JOIN benutzer). */
            erstellt_von_name?: string | null;
            /** Format: int64 */
            etb_nachforderung_id?: number | null;
            /** Format: int64 */
            id: number;
            /** @description Abgeleitet: status NOT IN ('eingetroffen','abgelehnt'). */
            ist_offen: boolean;
            prioritaet: components["schemas"]["Prioritaet"];
            status: components["schemas"]["NachforderungStatus"];
            unterwegs_at?: string | null;
            zugesagt_at?: string | null;
        };
        /**
         * @description Bedarfs-Status einer Nachforderung (Schema-Anker für die OpenAPI-Union, LFH-120).
         *     Wire == `status`.
         * @enum {string}
         */
        NachforderungStatus: "angefordert" | "zugesagt" | "unterwegs" | "eingetroffen" | "abgelehnt";
        /** @description Eine medizinische Verlaufsnotiz (1:1 zu `person_verlaufsnotiz`). */
        NotizAnzeige: {
            /** Format: int64 */
            einsatz_id: number;
            erfasst_at: string;
            /** Format: int64 */
            erfasst_von: number;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            person_id: number;
            text: string;
        };
        /**
         * @description Typ des belegenden Objekts. String = CHECK-Constraint in
         *     `migrations/0061_br_belegung.sql`.
         * @enum {string}
         */
        ObjektTyp: "einheit" | "fahrzeug";
        /**
         * @description Eine Offline-Karte als DB-Zeile (Admin-CRUD). `aktiv_basemap` = die von `/tiles` ausgelieferte
         *     Karte; `status` und die Download-Felder (groesse/sha256/download_at) pflegt LFH-181.
         */
        OfflineKarte: {
            aktiv_basemap: boolean;
            download_at?: string | null;
            /**
             * @description Kachel-Blob-Format (LFH-185): `pbf` (Vektor, gzip) oder `png`/`jpg`/`webp` (Raster). Steuert
             *     Content-Type + Encoding im Tile-Serving; orthogonal zu `kachel_schema` (Vektor-Layermenge).
             */
            format: string;
            /** Format: int64 */
            groesse?: number | null;
            /** Format: int64 */
            id: number;
            /**
             * @description Kachel-Schema der Datei (z.B. `'shortbread'`). **Aktuell inertes Metadatenfeld** (LFH-198):
             *     im Tile-Serving nicht konsumiert (MBTiles wird schema-blind gelesen), und alle Insert-Pfade
             *     setzen den Wert explizit — der DB-DEFAULT `'protomaps'` in Migration 0076 greift also nie.
             *     Bewusst behalten (statt teurem Table-Rebuild nur zum Default-Umlegen) für eine mögliche
             *     künftige Schema-Unterscheidung (z.B. Raster vs. Vektor, LFH-185); deren Nutzen hängt nicht
             *     am Default-Wert.
             */
            kachel_schema: string;
            lizenz?: string | null;
            name: string;
            pfad: string;
            quell_url?: string | null;
            sha256?: string | null;
            /** Format: int64 */
            sortier: number;
            status: components["schemas"]["OfflineKarteStatus"];
        };
        /**
         * @description GET /api/karte/offline-karten — alle Offline-Karten. Lesen: admin ODER Führungskraft (read-only).
         *     Listen-Antwort = DB-Zeile + Live-Download-Fortschritt. `geladen`/`gesamt` (Bytes) kommen nur
         *     für `status='laedt'` aus dem transienten In-Memory-State (keine DB-Spalte); `gesamt` ist
         *     `null`, wenn die Quelle keine Content-Length lieferte. Das Frontend rendert daraus den
         *     Fortschrittsbalken.
         */
        OfflineKarteAntwort: components["schemas"]["OfflineKarte"] & {
            /** Format: int64 */
            geladen?: number | null;
            /** Format: int64 */
            gesamt?: number | null;
            /** @description SHA256-Pin der aktuellen Katalog-URL (für den verifizierten Re-Download beim Update). */
            katalog_sha256?: string | null;
            /** @description Aktuelle Katalog-URL dieser Karte, wenn ein Update verfügbar ist (für den Re-Download). */
            katalog_url?: string | null;
            /**
             * @description True, wenn der Katalog für DIESELBE Karte (über den Namen) inzwischen eine ANDERE (neuere)
             *     Quell-URL führt als die installierte `quell_url` → im UI „Update verfügbar". Offline-Check
             *     (rein gegen den eingebauten Katalog, kein Netz). Lädt der Katalog/Mirror einen neueren
             *     Stand (anderes Datum in der URL), wird das hier automatisch sichtbar.
             */
            update_verfuegbar: boolean;
        };
        /**
         * @description Lebenszyklus-Status einer Offline-Karte. **Reiner Schema-Anker** (LFH-265): der Speichertyp
         *     bleibt `String` (`OfflineKarte.status` kommt per `sqlx::FromRow` aus der DB, wo der CHECK aus
         *     `migrations/0076_karte_registry.sql:45-46` die Wertemenge bereits fixiert). Ein echtes Enum
         *     im FromRow-Pfad würde ~8 `query_as::<_, OfflineKarte>`-Stellen gegen einen von der DB
         *     garantierten Wert fallibel machen — Kosten/Nutzen kippt eindeutig.
         * @enum {string}
         */
        OfflineKarteStatus: "registriert" | "laedt" | "bereit" | "fehler";
        /**
         * @description Ein kuratierter, herunterladbarer Offline-Karten-Vorschlag (LFH-181). `groesse` ist die
         *     UNGEFÄHRE Dateigröße in Bytes (für den Plattenplatz-Check vorab; die exakte Größe liefert
         *     die Content-Length bzw. der fertige Download). Einträge sind Shortbread-MBTiles (LFH-195)
         *     und rendern mit dem beschrifteten Offline-Style (Shortbread-Layer + eingebettete Glyphs/Sprite).
         */
        OfflineKatalogEintrag: {
            /** Format: int64 */
            groesse: number;
            /**
             * @description Optionale UX-Gruppe für die geführte Auswahl (z. B. „Deutschland", „DACH",
             *     „Bundesländer"). Rein für die Frontend-Gruppierung; `None` = ungruppiert (LFH-199).
             */
            gruppe?: string | null;
            kachel_schema: string;
            lizenz: string;
            name: string;
            /** @description Provenienz-Hinweis fürs UI (Eigenbau via karten-build/Planetiler, kein Community-Repo mehr). */
            quelle: string;
            region: string;
            /**
             * @description Optionaler SHA256-Pin (hex, lowercase). Gesetzt beim Eigen-Mirror: der Download
             *     verifiziert den berechneten gegen diesen Hash. `None` = kein Pin (vor erstem Release-Pin).
             */
            sha256?: string | null;
            url: string;
        };
        /**
         * @description Eine gemeinsam angezeigte Offline-Region im Config-Vertrag (LFH-188). `tiles_url` ist
         *     region-adressiert (`/api/karte/offline/{karte_id}/tiles/{z}/{x}/{y}?v=<token>`), sodass das
         *     Frontend je Region eine eigene Vector-Source mit eigenem Cache-Bust bindet.
         */
        OfflineRegionConfig: {
            attribution?: string | null;
            /** @description `"vektor"` (pbf) oder `"raster"` (png/jpg/webp) — steuert die Style-Wahl je Region. */
            format: components["schemas"]["OnlineStyleTyp"];
            /** Format: int64 */
            karte_id: number;
            /**
             * Format: int32
             * @description Maximaler Zoom der Vector-Source: Regional-Packs `14` (Shortbread-Voll-Detail), die
             *     Welt-Übersicht `6` (Low-Zoom-Basis, LFH-207) → MapLibre überzoomt sie darüber als Kontext.
             */
            maxzoom: number;
            name: string;
            tiles_url: string;
        };
        /**
         * @description Eine Online-Quelle als DB-Zeile (Admin-CRUD; trägt `id`/`sortier`/`aktiv`, anders als das
         *     schlanke Laufzeit-`OnlineStyle`). `typ` bleibt als SPEICHERTYP String ('vektor'|'raster') —
         *     serialisiert lowercase wie im Frontend-Vertrag, im OpenAPI-Schema per `value_type` als
         *     `OnlineStyleTyp`-Union verankert; Validierung der Werte weiterhin im Handler (LFH-265).
         */
        OnlineQuelle: {
            aktiv: boolean;
            attribution?: string | null;
            /** Format: int64 */
            id: number;
            name: string;
            /**
             * @description Serverseitig proxen (key-basierte Anbieter): `/config` gibt nur relative Proxy-URLs aus,
             *     die Upstream-`url` (inkl. Key) bleibt server-seitig (LFH-182).
             */
            proxy: boolean;
            /** Format: int64 */
            sortier: number;
            typ: components["schemas"]["OnlineStyleTyp"];
            url: string;
        };
        /**
         * @description Ein benannter Online-Basemap-View. `attribution` ist die config-autoritative
         *     Pflicht-Attribution, die das Frontend per `customAttribution` anzeigt.
         */
        OnlineStyle: {
            /** @description LFH-265: absent statt present-null, damit der generierte `attribution?` ehrlich ist. */
            attribution?: string | null;
            name: string;
            /**
             * @description `#[schema(required)]` (LFH-265): `typ` wird IMMER serialisiert — `#[serde(default)]`
             *     betrifft nur die Eingaberichtung (Katalog-Manifeste ohne `typ`), täuschte utoipa aber
             *     Optionalität vor. `skip_serializing_if` ist hier NICHT anwendbar (kein `Option<T>`);
             *     es würde `typ` beim Default `vektor` weglassen — eine echte Wire-Verschlechterung.
             */
            typ: components["schemas"]["OnlineStyleTyp"];
            url: string;
        };
        /**
         * @description Typ eines Online-Views: Vektor-Style-JSON (URL direkt an MapLibre) oder
         *     Raster-Tile-Template (`{z}/{y}/{x}`, das das Frontend in einen Raster-Style verpackt).
         * @enum {string}
         */
        OnlineStyleTyp: "vektor" | "raster";
        /** @description API-Darstellung der Org-Einstellungen (flach, alle Felder serialisiert). */
        OrgEinstellungenAnzeige: {
            auftrag_nummer_praefix?: string | null;
            /** Format: int64 */
            auftrag_quittierung_frist_min?: number | null;
            /** Format: int64 */
            auto_etb_eintraege?: number | null;
            einheiten?: null | components["schemas"]["EinheitenSystem"];
            etb_nummer_praefix?: string | null;
            geaendert_at?: string | null;
            /** Format: int64 */
            geaendert_von?: number | null;
            geocoder_url?: string | null;
            koordinatenformat?: null | components["schemas"]["Koordinatenformat"];
            /** Format: int64 */
            meldung_bestaetigung_frist_min?: number | null;
            meldung_nummer_praefix?: string | null;
            /** Format: int64 */
            org_id: number;
            /** Format: int64 */
            retention_dauer_tage?: number | null;
            zeitformat?: null | components["schemas"]["Zeitformat"];
            zeitzone?: string | null;
        };
        /**
         * @description Schlanke API-Darstellung für den Einsatz-Endpoint: nur Konventions-Felder,
         *     KEIN `geaendert_at`, KEIN `geaendert_von` — Audit-Schutz für Non-Admin-Mitglieder.
         */
        OrgEinstellungenHinweis: {
            auftrag_nummer_praefix?: string | null;
            /** Format: int64 */
            auftrag_quittierung_frist_min?: number | null;
            /** Format: int64 */
            auto_etb_eintraege?: number | null;
            einheiten?: null | components["schemas"]["EinheitenSystem"];
            etb_nummer_praefix?: string | null;
            koordinatenformat?: null | components["schemas"]["Koordinatenformat"];
            /** Format: int64 */
            meldung_bestaetigung_frist_min?: number | null;
            meldung_nummer_praefix?: string | null;
            /** Format: int64 */
            org_id: number;
            /** Format: int64 */
            retention_dauer_tage?: number | null;
            zeitformat?: null | components["schemas"]["Zeitformat"];
            zeitzone?: string | null;
        };
        /**
         * @description Org-weite Rolle (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `org_rolle`.
         * @enum {string}
         */
        OrgRolle: "fuehrungskraft" | "keine";
        /** @description Org-Stammdaten inkl. DV-102-Org-Default (`tz_organisation`). */
        OrganisationAnzeige: {
            /** Format: int64 */
            id: number;
            name: string;
            tz_organisation?: string | null;
        };
        /**
         * @description LFH-265: beide Felder werden ABSENT statt present-null serialisiert, damit der generierte
         *     `peilung?`/`ortsname?` ehrlich ist. Wire-Änderung — gepinnt per `contains_key` in
         *     `tests/ort_vorschau.rs` (ein `assert_eq!(v["ortsname"], Value::Null)` unterscheidet
         *     fehlenden Key nicht von null und wäre hier blind).
         */
        OrtVorschauAntwort: {
            ortsname?: string | null;
            peilung?: null | components["schemas"]["PeilungAntwort"];
        };
        PeilungAntwort: {
            bezug_label: string;
            /** Format: double */
            distanz_m: number;
            richtung: string;
        };
        /**
         * @description Serialisierbarer Personen-Datensatz (1:1 zur Tabelle `einsatz_person`; kein
         *     `org_id`, da einsatz-scoped). Direkt aus der Zeile lesbar — kein Stamm-Join,
         *     kein Snapshot wie bei Material.
         */
        PersonAnzeige: {
            aktuelle_sichtung?: null | components["schemas"]["Sichtungskategorie"];
            aktuelle_sichtung_at?: string | null;
            /** Format: int64 */
            aktuelle_uhs_id?: number | null;
            /** Format: int64 */
            aktueller_platz_id?: number | null;
            aktueller_verbleib?: string | null;
            /** Format: int64 */
            alter_geschaetzt?: number | null;
            antreff_ort?: string | null;
            /** Format: int64 */
            einsatz_id: number;
            erfasst_at: string;
            /** Format: int64 */
            erfasst_von: number;
            geaendert_at: string;
            /** Format: int64 */
            geaendert_von: number;
            geburtsdatum?: string | null;
            geschlecht?: null | components["schemas"]["Geschlecht"];
            herkunft_adresse?: string | null;
            /** Format: int64 */
            id: number;
            melder_kontakt?: string | null;
            name?: string | null;
            notiz?: string | null;
            /** Format: int64 */
            registrier_nr: number;
            status: components["schemas"]["PersonStatus"];
            storniert_at?: string | null;
            vorname?: string | null;
        };
        /**
         * @description Detail-Antwort: E‑1-Personenfelder (flatten) + E‑2-Verlauf-Arrays. Genau eine
         *     Antwort, genau ein `detail`-Audit (Spec-Annahme „Lesen / Lese-Audit").
         */
        PersonDetail: components["schemas"]["PersonAnzeige"] & {
            abgleiche: components["schemas"]["AbgleichAnzeige"][];
            notizen: components["schemas"]["NotizAnzeige"][];
            sichtungen: components["schemas"]["SichtungAnzeige"][];
            verbleib: components["schemas"]["VerbleibAnzeige"][];
        };
        /**
         * @description Administrative Status-Maschine einer Person (E‑1). E‑2 ergänzt die
         *     medizinische Sichtungskategorie SK I–IV als separates Attribut auf
         *     `betroffen` — diese Maschine bleibt unangetastet.
         * @enum {string}
         */
        PersonStatus: "erfasst" | "vermisst" | "betroffen" | "verstorben" | "abgemeldet";
        /** @description Öffentliche Personal-Darstellung (ohne `org_id`), inkl. aufgelöster Qualifikationen. */
        PersonalAnzeige: {
            angelegt_at: string;
            bemerkung?: string | null;
            /** Format: int64 */
            benutzer_id?: number | null;
            dienststatus: components["schemas"]["Dienststatus"];
            /** Format: int64 */
            id: number;
            name: string;
            personalnummer?: string | null;
            qualifikationen: components["schemas"]["QualifikationRef"][];
            staerke_position?: null | components["schemas"]["StaerkePosition"];
            telefon?: string | null;
            traegerorganisation?: string | null;
        };
        /** @description Personal-Status-Katalog-Eintrag (org-weit). Schema wie `FahrzeugStatus` minus `fms_anker`. */
        PersonalStatus: {
            farbe?: string | null;
            /** Format: int64 */
            id: number;
            kategorie: components["schemas"]["StatusKategorie"];
            label: string;
            /** Format: int64 */
            sortier: number;
        };
        /**
         * @description Abgeleitete AutoComplete-Vorschläge für die Trägerorganisation (DISTINCT, org-weit).
         *     Bewusst nur ein Feld (anders als FahrzeugVorschlaege mit drei Feldern).
         */
        PersonalVorschlaege: {
            traegerorganisation: string[];
        };
        /** @description Serialisierbare Platz-Anzeige (1:1 zur Tabelle). */
        PlatzAnzeige: {
            bezeichnung: string;
            /** Format: int64 */
            id: number;
            /** Format: double */
            pos_x?: number | null;
            /** Format: double */
            pos_y?: number | null;
            /** Format: int64 */
            reserviert_fuer_person_id?: number | null;
            storniert_at?: string | null;
            typ: components["schemas"]["PlatzTyp"];
            /** Format: int64 */
            uhs_id: number;
            verfuegbarkeit: components["schemas"]["Verfuegbarkeit"];
        };
        /**
         * @description Typ eines Platzes innerhalb einer UHS. String = CHECK-Constraint in
         *     `migrations/0028_uhs_platz.sql`. „Eingang"/„Inbox" ist KEIN Typ — die
         *     Inbox ist implizit über `platz_id = NULL` in der Belegung modelliert.
         * @enum {string}
         */
        PlatzTyp: "wartebereich" | "behandlungsplatz" | "bett" | "intensivplatz" | "trage" | "transport_bereitstellung" | "sonstige";
        /**
         * @description Geteilte Priorität für Auftrag/Meldung/Nachforderung (Schema-Anker für die OpenAPI-Union,
         *     LFH-120; TS: `AuftragPrioritaet`/`MeldungPrioritaet`/`NachforderungPrioritaet`). Wire == `prioritaet`.
         * @enum {string}
         */
        Prioritaet: "sofort" | "dringend" | "normal";
        /**
         * @description Qualifikations-Katalog-Eintrag (org-weit). `aktiv` wird nicht serialisiert
         *     (Listen-Endpunkt liefert ohnehin nur aktive).
         */
        Qualifikation: {
            /** Format: int64 */
            id: number;
            label: string;
            /** Format: int64 */
            sortier: number;
        };
        /**
         * @description Aufgelöste Qualifikation einer Person (id + label), inkl. deaktivierter
         *     Zuordnungen (deaktivierte Qualifikation bleibt in der Anzeige sichtbar).
         */
        QualifikationRef: {
            /** Format: int64 */
            id: number;
            label: string;
        };
        /**
         * @description Eine vom zentralen karten-service baubare Region (LFH-323, verschoben aus `karten-service`).
         *     Auf `String`-Felder umgebaut (vorher `&'static str`), damit `lifeline-hub` die Proxy-Antwort
         *     deserialisieren kann; `karten-service`s `dtos()` klont die `alle()`-Refs entsprechend.
         */
        RegionDto: {
            gruppe: string;
            name: string;
            region: string;
            slug: string;
        };
        /**
         * @description Geteilte Richtung für Auftrag/Meldung (Schema-Anker für die OpenAPI-Union, LFH-120).
         *     Wire == `richtung`.
         * @enum {string}
         */
        Richtung: "intern" | "extern";
        /** @enum {string} */
        SchadenAbschlussGrund: "behoben" | "kein_handlungsbedarf" | "abgewiesen";
        SchadenAnzeige: {
            abschluss_at?: string | null;
            abschluss_grund?: null | components["schemas"]["SchadenAbschlussGrund"];
            ausmass: components["schemas"]["Ausmass"];
            beschreibung: string;
            /** Format: int64 */
            einsatz_id: number;
            erfasst_at: string;
            /** Format: int64 */
            erfasst_von: number;
            geaendert_at: string;
            /** Format: int64 */
            geaendert_von: number;
            geschaedigt_kontakt?: string | null;
            /** Format: int64 */
            geschaedigt_organisation_id?: number | null;
            geschaedigt_organisation_name?: string | null;
            /** Format: int64 */
            geschaedigt_person_id?: number | null;
            /** Format: int64 */
            geschaedigt_personal_id?: number | null;
            geschaedigt_personal_name?: string | null;
            /** Format: int64 */
            geschaedigt_registrier_nr?: number | null;
            geschaedigt_storniert_at?: string | null;
            /** Format: int64 */
            id: number;
            /** Format: double */
            lat?: number | null;
            /** Format: double */
            lon?: number | null;
            ort: string;
            /** Format: int64 */
            registrier_nr: number;
            status: components["schemas"]["SchadenStatus"];
            storniert_at?: string | null;
            /** Format: int64 */
            storniert_von?: number | null;
            typ: components["schemas"]["SchadenTyp"];
            uebergeben_an?: string | null;
            uebergeben_at?: string | null;
        };
        /** @enum {string} */
        SchadenStatus: "offen" | "uebergeben" | "abgeschlossen";
        /** @enum {string} */
        SchadenTyp: "sachschaden" | "verkehrshindernis" | "infrastruktur" | "umweltschaden" | "tierkadaver" | "sonstige";
        /**
         * @description Schutzobjekt (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `schutzobjekt`.
         * @enum {string}
         */
        Schutzobjekt: "menschen" | "tiere" | "umwelt" | "sachwerte" | "einsatzkraefte";
        /** @description Ein Sichtungs-Verlaufseintrag (1:1 zu `person_sichtung`). */
        SichtungAnzeige: {
            /** Format: int64 */
            einsatz_id: number;
            gesichtet_at: string;
            /** Format: int64 */
            gesichtet_von: number;
            /** Format: int64 */
            id: number;
            kategorie: components["schemas"]["Sichtungskategorie"];
            notiz?: string | null;
            /** Format: int64 */
            person_id: number;
        };
        /**
         * @description Medizinische Sichtungskategorie (Triage). String = CHECK-Constraint in
         *     `migrations/0023_person_sichtung.sql`. **`Tot` ist ein medizinisches Urteil
         *     und ändert den Admin-`PersonStatus` NICHT** (Annahme 4).
         * @enum {string}
         */
        Sichtungskategorie: "sk1" | "sk2" | "sk3" | "sk4" | "tot" | "unverletzt";
        /**
         * @description Spezies-Enum. String = CHECK-Constraint. `etb_label` ist die pseudonyme
         *     Anzeige in der ETB-Spur (z. B. "Hund").
         * @enum {string}
         */
        Spezies: "hund" | "katze" | "grosstier" | "nutzgefluegel" | "kleintier" | "wildtier" | "sonstige";
        /** @description Öffentliche Sprechgruppen-Darstellung (ohne `org_id`, mit `einsatz_lokal`-Flag). */
        SprechgruppeAnzeige: {
            aktiv: boolean;
            betriebsart: components["schemas"]["Betriebsart"];
            bezeichnung: string;
            /** Format: int64 */
            einsatz_id?: number | null;
            /** @description `true` wenn die Sprechgruppe einsatzlokal ist (d.h. `einsatz_id` gesetzt). */
            einsatz_lokal: boolean;
            hinweis?: string | null;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            sortier: number;
        };
        /**
         * @description Taktische Stärke (FwDV 3 / DV 100): Führer / Unterführer / Mannschaft.
         *     `gesamt` wird berechnet, nicht gespeichert. `u16`, damit auch ein Verband/Stab
         *     über 255 nicht anstößt. Wiederverwendbar für Personal/Einheiten (K&M‑2/3).
         */
        Staerke: {
            /** Format: int32 */
            fuehrer: number;
            /** Format: int32 */
            mannschaft: number;
            /** Format: int32 */
            unterfuehrer: number;
        };
        /**
         * @description Taktische Stärke-Position einer einzelnen Person (genau einer von drei Töpfen).
         *     Wird als TEXT in der DB gespeichert (kein sqlx-Enum-Decode → manuell konvertiert).
         * @enum {string}
         */
        StaerkePosition: "fuehrer" | "unterfuehrer" | "mannschaft";
        /**
         * @description Status-Kategorie eines Katalog-Eintrags (Schema-Anker für die OpenAPI-Union, LFH-120).
         *     Wire == `status_kategorie`.
         * @enum {string}
         */
        StatusKategorie: "verfuegbar" | "gebunden" | "nicht_verfuegbar";
        /** @description Org-weiter Einsatzstichwort-Vorschlag für die Combobox. */
        StichwortVorschlag: {
            /** Format: int64 */
            id: number;
            text: string;
        };
        /**
         * @description System-Rolle (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `system_rolle`.
         * @enum {string}
         */
        SystemRolle: "admin" | "keiner";
        /**
         * @description Serialisierbarer Tier-Datensatz (1:1 zur Tabelle `einsatz_tier`). Die beiden
         *     `halter_*`-Felder kommen aus einem LEFT JOIN auf `einsatz_person` und sind
         *     read-only (NULL bei Freitext-Halter oder unbekannt) — die UI zeigt damit
         *     `R-nnn` bzw. "Halter (storniert): R-nnn" ohne Zweit-Request.
         */
        TierAnzeige: {
            abschluss_grund?: null | components["schemas"]["AbschlussGrund"];
            abschluss_ziel?: string | null;
            /** Format: int64 */
            alter_geschaetzt?: number | null;
            antreff_ort?: string | null;
            /** Format: int64 */
            einsatz_id: number;
            erfasst_at: string;
            /** Format: int64 */
            erfasst_von: number;
            farbe_beschreibung?: string | null;
            geaendert_at: string;
            /** Format: int64 */
            geaendert_von: number;
            geschlecht?: null | components["schemas"]["TierGeschlecht"];
            groesse_gewicht?: string | null;
            halter_kontakt?: string | null;
            /** Format: int64 */
            halter_person_id?: number | null;
            /** Format: int64 */
            halter_registrier_nr?: number | null;
            halter_storniert_at?: string | null;
            /** Format: int64 */
            id: number;
            kennzeichnung?: string | null;
            notiz?: string | null;
            rasse_beschreibung?: string | null;
            /** Format: int64 */
            registrier_nr: number;
            rufname?: string | null;
            spezies: components["schemas"]["Spezies"];
            status: components["schemas"]["TierStatus"];
            storniert_at?: string | null;
        };
        /**
         * @description Optionale Geschlechtsangabe des Tiers (kein `divers`, anders als bei Personen).
         * @enum {string}
         */
        TierGeschlecht: "maennlich" | "weiblich" | "unbekannt";
        /**
         * @description Status-Maschine eines Tiers (E‑4). Bewusst schlank — keine Sichtungskette wie
         *     bei Personen. String = CHECK-Constraint in `migrations/0031_einsatz_tier.sql`.
         * @enum {string}
         */
        TierStatus: "aktiv" | "vermisst" | "abgeschlossen";
        /**
         * @description Antwort auf `POST /api/auth/totp/enroll/finish` (LFH-43, Task 4): die frisch erzeugten
         *     Recovery-Codes im KLARTEXT — werden NUR HIER, EINMALIG zurückgegeben. Ab dem nächsten
         *     Request existieren nur noch ihre sha256-Hashes in `totp_recovery_code`
         *     (`totp::storage::speichere_recovery_codes`); ein Verlust dieser Antwort ist nicht
         *     rekonstruierbar (Betriebs-Hinweis: Frontend muss die Codes eindringlich anzeigen).
         */
        TotpEnrollFinish: {
            recovery_codes: string[];
        };
        /**
         * @description Antwort auf `POST /api/auth/totp/enroll/start` (LFH-43, Task 4): das frisch erzeugte,
         *     noch NICHT aktive TOTP-Secret. `otpauth_url` ist für den QR-Code-Scan gedacht,
         *     `secret_base32` als Klartext-Fallback zum manuellen Eintragen in die Authenticator-App.
         */
        TotpEnrollStart: {
            otpauth_url: string;
            secret_base32: string;
        };
        /** @description Serialisierbare UHS-Anzeige (1:1 zur Tabelle, ohne abgeleitete Felder). */
        UhsAnzeige: {
            /** Format: int64 */
            abschnitt_id?: number | null;
            bezeichnung: string;
            /** Format: int64 */
            einsatz_id: number;
            erfasst_at: string;
            /** Format: int64 */
            erfasst_von: number;
            geaendert_at: string;
            /** Format: int64 */
            geaendert_von: number;
            /** Format: int64 */
            id: number;
            /** Format: double */
            lat?: number | null;
            /** Format: double */
            lon?: number | null;
            notiz?: string | null;
            standort?: string | null;
            status: components["schemas"]["UhsStatus"];
            storniert_at?: string | null;
            /** @description LFH-120: Wire ist `String`; Override zeigt aufs Enum, damit die Union erhalten bleibt. */
            typ: components["schemas"]["UhsTyp"];
        };
        /** @description Detail-Antwort: UHS-Stamm + Plätze + aktuelle Belegungen + zugeordnetes Material. */
        UhsDetail: components["schemas"]["UhsAnzeige"] & {
            belegungen: components["schemas"]["BelegungAnzeige"][];
            material: components["schemas"]["EinsatzMaterialAnzeige"][];
            plaetze: components["schemas"]["PlatzAnzeige"][];
        };
        /**
         * @description Status einer UHS. String = CHECK-Constraint. `aufgeloest` ist terminal.
         * @enum {string}
         */
        UhsStatus: "geplant" | "aktiv" | "aufgeloest";
        /**
         * @description Typ einer Unfallhilfsstelle. String = CHECK-Constraint in
         *     `migrations/0027_uhs.sql`.
         *
         *     LFH-120: `rename_all` richtet die (bislang ungenutzte) Serde-Serialisierung an
         *     den `as_str()`-Wire-Werten aus, damit das utoipa-Schema die snake_case-Union trifft.
         * @enum {string}
         */
        UhsTyp: "patientenablage" | "behandlungsplatz" | "verletztensammelstelle" | "sonstige";
        /** @description Ein Verbleib-Ereignis (1:1 zu `person_verbleib`). */
        VerbleibAnzeige: {
            art: components["schemas"]["VerbleibArt"];
            /** Format: int64 */
            einsatz_id: number;
            /** Format: int64 */
            erfasst_von: number;
            /** Format: int64 */
            id: number;
            notiz?: string | null;
            /** Format: int64 */
            person_id: number;
            status?: null | components["schemas"]["VerbleibStatus"];
            transportmittel?: string | null;
            zeitpunkt_at: string;
            ziel?: string | null;
        };
        /**
         * @description Art eines Verbleib-Ereignisses. String = CHECK-Constraint in
         *     `migrations/0025_person_verbleib.sql`. `Verstorben` = Verbleib des Leichnams
         *     (NICHT der Admin-Status).
         * @enum {string}
         */
        VerbleibArt: "transport" | "entlassung" | "vor_ort" | "verstorben";
        /**
         * @description Verbleib-Status (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `status`.
         * @enum {string}
         */
        VerbleibStatus: "angemeldet" | "abtransportiert";
        /**
         * @description Verfügbarkeit eines Platzes (getrennt von Belegung). String = CHECK in
         *     `migrations/0028_uhs_platz.sql`. `reserviert` ist im DB-CHECK an
         *     `reserviert_fuer_person_id IS NOT NULL` gekoppelt.
         * @enum {string}
         */
        Verfuegbarkeit: "frei" | "defekt" | "aufbereitung" | "gesperrt" | "reserviert";
        /**
         * @description Eine im karten_dir vorhandene, aber noch nicht registrierte MBTiles-Datei — Kandidat für den
         *     lokalen Import gebauter Region-Packs (LFH-199, ohne Download/Hosting).
         */
        VorhandeneKarte: {
            dateiname: string;
            /** Format: int64 */
            groesse: number;
        };
        /**
         * @description Warnstufe (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `warnstufe`.
         * @enum {string}
         */
        Warnstufe: "keine" | "niedrig" | "mittel" | "hoch" | "akut";
        /**
         * @description Zeitformat (Schema-Anker für die OpenAPI-Union, LFH-120). Wire == `zeitformat`
         *     (per-Variante, `rename_all` trifft die Ziffern-Kürzel nicht).
         * @enum {string}
         */
        Zeitformat: "24h" | "12h";
        /** @description Ein Audit-Eintrag mit aufgelöstem Benutzernamen (für die Audit-Einsicht). */
        ZugriffAnzeige: {
            art: components["schemas"]["ZugriffArt"];
            /** Format: int64 */
            benutzer_id: number;
            benutzer_name: string;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            person_id?: number | null;
            zugriff_at: string;
        };
        /**
         * @description LFH-120: Schema-Anker für die `art`-Union. Wire = DB-CHECK
         *     `art IN ('detail','export')` (migrations/0021_person_zugriff_audit.sql).
         * @enum {string}
         */
        ZugriffArt: "detail" | "export";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
